# Generated by Django 2.2.1 on 2019-07-01 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('image', models.ImageField(default='', max_length=200, upload_to='images', verbose_name='Image File')),
                ('position', models.SmallIntegerField(blank=True, default=0, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('position',),
            },
        ),
    ]
